### ISSUE TITLE
Plot sample size dist 

### ISSUE THREAD

**Issue by max-pilz** [imbi-heidelberg/blindrecalc#23]
@lbau7 

warum kann man die Fallzahlverteilung nicht plotten wenn n1 und nuisance laenge 1 haben?

https://github.com/imbi-heidelberg/blindrecalc/blob/103894fa398a98d2018e3e221b4ca6ce66344000/R/ChiSquare.R#L236-L238

Kann man das eventuell noch einfuegen?

**Comment by lbau7** [comment]
Ja, das ist mir auch schon aufgefallen. Gut, dass du das nochmal sagst! Werde ich ausbessern.

**Comment by max-pilz** [comment]
cf. #24
